version: '3.7'

networks:
  resources:
    external: true

services:
  front:
    image: iriskin/laboratory-reestr-front:latest
    ports:
      - "80"
    networks:
      - resources
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.laboratory-django.rule=Host(`laboratory.kvd-rostov.ru`)"
      - "traefik.http.routers.laboratory-django.entrypoints=https"
      - "traefik.http.routers.laboratory-django.tls=true"
    restart: always
