version: "3.7"

services:
    router:
        build:
            context: .
            dockerfile: Dockerfile
        # image: nginx
        # volumes:
        #     - ./config.conf /etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
